export type ExplodeDirection =
  | "upper-left"
  | "upper-right"
  | "lower-left"
  | "lower-right"
  | "up"
  | "down";

export type FloatingPhoto = {
  id: string;
  src: string;
  alt: string;
  /** Position (% of viewport) */
  x: number;
  y: number;
  /** Parallax depth — higher = more mouse movement */
  depth: number;
  rotate: number;
  w: number;
  h: number;
  direction: ExplodeDirection;
  speed: number;
  /** Stagger delay for entrance (seconds) */
  enterDelay: number;
};

const hero = (file: string) => `/images/hero/${file}`;

/** Personal photos — positions keep the center clear for the headline */
export const FLOATING_PHOTOS: FloatingPhoto[] = [
  {
    id: "snow-purple",
    src: hero("02-snow.png"),
    alt: "Khang in the snow",
    x: 5,
    y: 10,
    depth: 0.6,
    rotate: -7,
    w: 118,
    h: 148,
    direction: "upper-left",
    speed: 1.05,
    enterDelay: 0.5,
  },
  {
    id: "hackathon",
    src: hero("05-hackathon.png"),
    alt: "Coding with friends",
    x: 84,
    y: 8,
    depth: 0.8,
    rotate: 9,
    w: 132,
    h: 168,
    direction: "upper-right",
    speed: 1.15,
    enterDelay: 0.58,
  },
  {
    id: "lake",
    src: hero("10-lake.png"),
    alt: "Lake trip with friends",
    x: 8,
    y: 26,
    depth: 0.7,
    rotate: 5,
    w: 120,
    h: 152,
    direction: "upper-left",
    speed: 1.08,
    enterDelay: 0.66,
  },
  {
    id: "stage",
    src: hero("12-stage.png"),
    alt: "On stage with friends",
    x: 88,
    y: 30,
    depth: 0.75,
    rotate: -10,
    w: 126,
    h: 158,
    direction: "upper-right",
    speed: 1.12,
    enterDelay: 0.74,
  },
  {
    id: "bereal-group",
    src: hero("14-bereal-group.png"),
    alt: "BeReal with friends",
    x: 72,
    y: 5,
    depth: 0.5,
    rotate: 6,
    w: 112,
    h: 140,
    direction: "up",
    speed: 1.0,
    enterDelay: 0.62,
  },
  {
    id: "snow-selfie",
    src: hero("13-snow-selfie.png"),
    alt: "Winter hike selfie",
    x: 4,
    y: 44,
    depth: 0.65,
    rotate: -5,
    w: 124,
    h: 156,
    direction: "upper-left",
    speed: 1.1,
    enterDelay: 0.82,
  },
  {
    id: "auditorium",
    src: hero("06-auditorium.png"),
    alt: "With friends at an event",
    x: 78,
    y: 16,
    depth: 0.55,
    rotate: 11,
    w: 116,
    h: 146,
    direction: "upper-right",
    speed: 0.95,
    enterDelay: 0.7,
  },
  {
    id: "dinner",
    src: hero("09-dinner.png"),
    alt: "Dinner with friends",
    x: 6,
    y: 70,
    depth: 0.6,
    rotate: 4,
    w: 128,
    h: 162,
    direction: "lower-left",
    speed: 1.05,
    enterDelay: 0.9,
  },
  {
    id: "sunglasses",
    src: hero("11-sunglasses.png"),
    alt: "Friends at a store",
    x: 86,
    y: 66,
    depth: 0.58,
    rotate: -8,
    w: 114,
    h: 144,
    direction: "lower-right",
    speed: 1.08,
    enterDelay: 0.98,
  },
  {
    id: "gallery",
    src: hero("18-gallery.png"),
    alt: "At an art gallery",
    x: 14,
    y: 80,
    depth: 0.48,
    rotate: -4,
    w: 110,
    h: 138,
    direction: "lower-left",
    speed: 1.02,
    enterDelay: 1.06,
  },
  {
    id: "christmas",
    src: hero("17-christmas.png"),
    alt: "Holiday photo",
    x: 88,
    y: 76,
    depth: 0.52,
    rotate: 7,
    w: 118,
    h: 148,
    direction: "lower-right",
    speed: 1.1,
    enterDelay: 1.14,
  },
  {
    id: "friends-01",
    src: hero("01.png"),
    alt: "With friends outdoors",
    x: 3,
    y: 58,
    depth: 0.72,
    rotate: -6,
    w: 122,
    h: 154,
    direction: "lower-left",
    speed: 1.12,
    enterDelay: 0.86,
  },
  {
    id: "friends-19",
    src: hero("19.png"),
    alt: "Group photo",
    x: 74,
    y: 82,
    depth: 0.45,
    rotate: 5,
    w: 108,
    h: 136,
    direction: "lower-right",
    speed: 1.0,
    enterDelay: 1.1,
  },
  {
    id: "eating",
    src: hero("16-eating.png"),
    alt: "Casual moment with friends",
    x: 90,
    y: 46,
    depth: 0.62,
    rotate: 9,
    w: 114,
    h: 142,
    direction: "down",
    speed: 1.05,
    enterDelay: 0.94,
  },
  {
    id: "mirror",
    src: hero("15-mirror.png"),
    alt: "Mirror selfie",
    x: 10,
    y: 4,
    depth: 0.42,
    rotate: -3,
    w: 104,
    h: 130,
    direction: "up",
    speed: 0.98,
    enterDelay: 0.54,
  },
  {
    id: "bereal",
    src: hero("08-bereal.png"),
    alt: "BeReal selfie",
    x: 92,
    y: 12,
    depth: 0.5,
    rotate: -9,
    w: 106,
    h: 132,
    direction: "upper-right",
    speed: 1.0,
    enterDelay: 0.76,
  },
  {
    id: "restaurant",
    src: hero("07-restaurant.png"),
    alt: "At a restaurant",
    x: 5,
    y: 86,
    depth: 0.55,
    rotate: 6,
    w: 112,
    h: 140,
    direction: "lower-left",
    speed: 1.08,
    enterDelay: 1.18,
  },
  {
    id: "portrait-03",
    src: hero("03.png"),
    alt: "Portrait",
    x: 80,
    y: 54,
    depth: 0.68,
    rotate: -7,
    w: 116,
    h: 146,
    direction: "lower-right",
    speed: 1.1,
    enterDelay: 0.88,
  },
  {
    id: "portrait-04",
    src: hero("04.png"),
    alt: "Portrait",
    x: 2,
    y: 36,
    depth: 0.74,
    rotate: 8,
    w: 120,
    h: 150,
    direction: "upper-left",
    speed: 1.14,
    enterDelay: 0.78,
  },
];

export const EXPLODE_BASE: Record<
  ExplodeDirection,
  { x: number; y: number }
> = {
  "upper-left": { x: -520, y: -460 },
  "upper-right": { x: 540, y: -440 },
  "lower-left": { x: -500, y: 480 },
  "lower-right": { x: 560, y: 500 },
  up: { x: 20, y: -620 },
  down: { x: -30, y: 640 },
};
